insert into book_category(name, url_name) values('技術本', 'it');
insert into book_category(name, url_name) values('漫画', 'manga');


insert into book_subcategory(name, url_name, category_id) values('ジャンプ', 'jump', 2);
insert into book_subcategory(name, url_name, category_id) values('少年コミック', 'boy_comics', 2);
insert into book_subcategory(name, url_name, category_id) values('青年コミック', 'young_comics',2);
insert into book_subcategory(name, url_name, category_id) values('その他コミック', 'other_comics', 2);
insert into book_subcategory(name, url_name, category_id) values('Server', 'server', 1);
insert into book_subcategory(name, url_name, category_id) values('Linux', 'linux', 1);
insert into book_subcategory(name, url_name, category_id) values('Perl', 'perl', 1);
insert into book_subcategory(name, url_name, category_id) values('Python','python', 1);
insert into book_subcategory(name, url_name, category_id) values('Java','java', 1);
insert into book_subcategory(name, url_name, category_id) values('Network','network', 1);
insert into book_subcategory(name, url_name, category_id) values('Webdb_press','webdb_press', 1);
insert into book_subcategory(name, url_name, category_id) values('Softwear_desing','softwear_desing', 1);
insert into book_subcategory(name, url_name, category_id) values('その他','other', 1);


insert into book_entry(title, url_title, category_id, subcategory_id) values ('naruto', 'naruto', 2, 1);
insert into book_entry(title, url_title, category_id, subcategory_id) values ('鋼の錬金術師', 'hagaren', 2, 2);
insert into book_entry(title, url_title, category_id, subcategory_id) values ('エヴァンゲリオン', 'eva', 2, 2);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('ドラゴンボール', 'dragon_ball', 2, 1);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('one piece', 'one_piece', 2, 1);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('バガボンド', 'bagabondo', 2, 3);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('Emacsテクニックバイブル', 'emacs_rubikichi', 1, 13);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('DjangoxPython', 'django_python', 1, 8);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('サーバーインフラを支える技術', 'server_infra', 1, 5);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('Linuxアドバンスシステム構築ガイド', 'linux_ha1', 1, 5);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('ApacheStrutsアプリケーション開発入門', 'apache_struts', 1, 9);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('ふつうのLinuxプログラミング', 'linux_basic', 1, 6);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('zsh最強シェル', 'zsh_saikyou', 1, 13);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('xen徹底入門', 'xen_nyumon', 1, 5);
insert INTO book_entry(title, url_title, category_id, subcategory_id) VALUES ('kvm徹底入門', 'kvm_nyumon', 1, 5);

insert into book_writer(name) values('');
insert into book_writer(name) values('岸本斉史');
insert into book_writer(name) values('荒川弘');
insert into book_writer(name) values('貞本義行・GAINAX');
insert into book_writer(name) values('るびきち');
insert into book_writer(name) values('露木 誠');
insert into book_writer(name) values('伊藤直也ほか');
insert into book_writer(name) values('デージーネット');
insert into book_writer(name) values('四次元データ');
insert into book_writer(name) values('青木峰郎');
insert into book_writer(name) values('中島 能和');
insert into book_writer(name) values('宮本 久仁男');
insert into book_writer(name) values('平 初');

insert into book_publisher(name) values('');
insert into book_publisher(name) values('集英社');
insert into book_publisher(name) values('スクウェア・エニックス');
insert into book_publisher(name) values('角川コミックス');
insert into book_publisher(name) values('技術評論社');
insert into book_publisher(name) values('秀和システム');
insert into book_publisher(name) values('ソフトバンクパブリッシング');
insert into book_publisher(name) values('ソフトバンククリエイティブ');
insert into book_publisher(name) values('翔泳社');


insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  1, 24, 0, 195, 2, 2, '', '2011-05-07', '2011-05-07',true ,true);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  2, 59, 0, 202, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  3, 42, 0, 201, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  4, 38, 0, 175, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  5, 31, 0, 178, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  6, 45, 0, 186, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  7, 68, 0, 184, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  8, 60, 0, 184, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1,  9, 26, 0, 181, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 10, 29, 0, 187, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 11, 30, 0, 191, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 12, 32, 0, 199, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 13, 62, 0, 189, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 14, 60, 0, 180, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 15, 34, 0, 187, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 16, 54, 0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 17, 30, 0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 18, 31, 0, 197, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 19, 36, 0, 180, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 20, 40, 0, 181, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 21, 57, 0, 202, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 22, 55, 0, 181, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 23, 55, 0, 183, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 24, 51, 0, 180, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 25, 45, 0, 187, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 26, 49, 0, 176, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 27, 48, 0, 184, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 28, 45, 0, 182, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 29, 47, 0, 184, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 30, 54, 0, 182, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 31, 41, 0, 177, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 32, 41, 0, 187, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 33, 51, 0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 34, 93, 0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 35, 34, 0, 194, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 36, 36, 0, 188, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 37, 40, 0, 186, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 38, 51, 0, 182, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 39, 59, 0, 194, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 40, 56, 0,  99, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 41, 38, 0, 185, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 42, 62, 0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 43, 67, 0, 250, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 44, 53, 0, 192, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 45, 73, 0,  95, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 46,  0, 0,   0, 2, 2, '', '2011-05-07', '2011-05-07',false ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 47, 59, 0,  98, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 48, 64, 0, 106, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 49, 103,0, 193, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 50, 100,0, 191, 2, 2, '', '2011-05-07', '2011-05-07',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 51, 75, 0, 195, 2, 2, '', '2011-05-13', '2011-05-13',true ,false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(1, 52, 76, 0, 210, 2, 2, '', '2011-05-13', '2011-05-13',true ,false);


insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 1,  47, 0, 183, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 2,  44, 0, 188, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 3,  45, 0, 187, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 4,  44, 0, 193, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 5,  47, 0, 191, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 6,  35, 0, 190, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 7,  47, 0, 188, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 8,  52, 0, 177, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 9,  47, 0, 182, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 10, 51, 0, 187, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 11, 46, 0, 184, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 12, 55, 0, 185, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 13, 57, 0, 182, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 14, 54, 0, 192, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 15, 53, 0, 185, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 16, 52, 0, 189, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 17, 53, 0, 186, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 18, 31, 0, 187, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 19, 65, 0, 192, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 20, 65, 0, 195, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 21, 58, 0, 195, '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 22, 0,  0, 0,   '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 23, 0,  0, 0,   '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 24, 0,  0, 0,   '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 25, 0,  0, 0,   '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 26, 0,  0, 0,   '3', '3', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(2, 27, 81, 0, 216, '3', '3', '', '2011-05-07', '2011-05-07',false,false);


insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  1, 71, 0, 178, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  2, 68, 0, 178, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  3, 41, 0, 172, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  4, 35, 0, 187, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  5, 71, 0, 192, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  6, 67, 0, 188, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  7, 48, 0, 96,  '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  8, 30, 0, 176, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3,  9, 0,  0, 0,   '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3, 10, 0,  0, 0,   '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3, 11, 69, 0, 174, '4', '4', '', '2011-05-07', '2011-05-07',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(3, 12, 107,0, 181, '4', '4', '', '2011-05-07', '2011-05-07',false, false);

insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(7,  1, 0, 0, 0, '5', '5', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(8,  1, 0, 0, 0, '6', '5', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(9,  1, 0, 0, 0, '7', '5', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(10, 1, 0, 0, 0, '8', '6', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(11, 1, 0, 0, 0, '9', '7', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(12, 1, 0, 0, 0, '10', '8', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(13, 1, 0, 0, 0, '11', '9', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(14, 1, 0, 0, 0, '12', '9', '', '2011-05-08', '2011-05-08',false, false);
insert into book_entry_detail(entry_id, volume, pdf_size, epud_size, total_page, writer_id, publisher_id, description, create_date, update_date, exit_pdf, exit_epud)  values(15, 1, 0, 0, 0, '13', '9', '', '2011-05-08', '2011-05-08',false, false);


insert into top_whatnew (regist_date, content)values('2011-04-01', 'リニューアル');
insert into top_whatnew (regist_date, content)values('2011-04-02', 'bookに追加<br>  test1<br>  test2<br>  test3');
insert into top_whatnew (regist_date, content)values('2011-04-03', 'book情報を一部更新');
insert into top_whatnew (regist_date, content)values('2011-04-04', '技術本いろいろ追加');
insert into top_whatnew (regist_date, content)values('2011-04-05', '認証機能を追加');
insert into top_whatnew (regist_date, content)values('2011-04-06', 'musicに追加<br> <ul><li>sample1</li><li>sample2</li><li>sample3</li></ul>');
INSERT INTO top_whatnew (regist_date, content) values('2011-01-01','abc');
